### ISSUE TITLE
Episode 61 (dataviz) not working on the site 😞

### ISSUE THREAD

**Issue by RichardBray** [toolsday/toolsday-old#61]
Although you're able to download the episode from the homepage and it works in the RSS feed and iTunes, you aren't able to download it from the individual page `http://toolsday.io/episodes/dataviz.html`.

![screen shot 2017-11-17 at 09 29 19](https://user-images.githubusercontent.com/1377253/32940323-39e715cc-cb7a-11e7-889e-ad921ab7452e.png)

I tried to fix it myself and submit a PR but I don't know where the audio is hosted.

**Comment by chrisdhanaraj** [comment]
Thanks for this! Fixed it, should be rolling out soon
